version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: datastore-level
    versions:
    - 5.0.0
  - dependency-name: datastore-fs
    versions:
    - 4.0.0
  - dependency-name: datastore-core
    versions:
    - 4.0.0
  - dependency-name: interface-datastore
    versions:
    - 4.0.0
  - dependency-name: aegir
    versions:
    - 31.0.0
    - 31.0.1
    - 31.0.3
    - 32.0.2
    - 32.1.0
    - 32.2.0
    - 33.0.0
    - 33.1.0
  - dependency-name: memdown
    versions:
    - 6.0.0
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 10.0.1
  - dependency-name: p-queue
    versions:
    - 7.0.0
  - dependency-name: multibase
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: err-code
    versions:
    - 3.0.0
    - 3.0.1
