language: node_js
node_js:
  - "4"
  - "5"

branches:
  only:
    - master

before_install:
  - npm i -g npm
  # Workaround for a permissions issue with Travis virtual machine images
script:
  - npm run lint
  - npm test

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
