name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - packages/ipfs-repo
          - packages/ipfs-repo-migrations
      fail-fast: true
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - run: npm install
    - run: npm run build
    - run: npm run lint
    - run: npm run depcheck
    - uses: gozala/typescript-error-reporter-action@v1.0.8
      with:
        project: ${{ matrix.project }}
  test-node:
    needs: check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node: [14, 16]
        project:
          - packages/ipfs-repo
          - packages/ipfs-repo-migrations
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run test -- -- -- --cov -t node
      - uses: codecov/codecov-action@v1
        with:
            project: ${{ matrix.project }}
  test-electron-main:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - packages/ipfs-repo
          - packages/ipfs-repo-migrations
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
        with:
          project: ${{ matrix.project }}
      - run: npm install
      - run: npm run pretest
      - run: npx xvfb-maybe aegir test -t electron-main --bail -f dist/cjs/node-test/*js
  test-electron-renderer:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - packages/ipfs-repo
          - packages/ipfs-repo-migrations
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
        with:
          project: ${{ matrix.project }}
      - run: npm install
      - run: npm run pretest
      - run: npx xvfb-maybe aegir test -t electron-renderer --bail -f dist/cjs/browser-test/*js

