name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - run: npm install
    - run: npm run build
    - run: npm run lint
  test-node:
    needs: check
    runs-on: ${{ matrix.os }}
    name: Test ${{ matrix.project }} node
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node: [16]
        project:
          - ipfs-repo
          - ipfs-repo-migrations
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run test -- --scope=${{ matrix.project }} -- -- --cov -t node
  test-electron-main:
    needs: check
    runs-on: ubuntu-latest
    name: Test ${{ matrix.project }} electron-main
    strategy:
      matrix:
        project:
          - ipfs-repo
          - ipfs-repo-migrations
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run pretest
      - run: npx xvfb-maybe npm run test -- --scope=${{ matrix.project }} -- -- -t electron-main --bail -f dist/cjs/node-test/*js
  test-electron-renderer:
    needs: check
    runs-on: ubuntu-latest
    name: Test ${{ matrix.project }} electron-renderer
    strategy:
      matrix:
        project:
          - ipfs-repo
          - ipfs-repo-migrations
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
        with:
          project: ${{ matrix.project }}
      - run: npm install
      - run: npm run pretest
      - run: npx xvfb-maybe npm run test -- --scope=${{ matrix.project }} -- -- -t electron-renderer --bail -f dist/cjs/browser-test/*js

