name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - run: npm install
    - run: npm run build
    - run: npm run lint
    - run: npm run depcheck
  test-node:
    needs: check
    runs-on: ${{ matrix.os }}
    name: Test ${{ matrix.project }} node
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node: [16]
        project:
          - ipfs-repo
          - ipfs-repo-migrations
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run test -- --scope=${{ matrix.project }} -- -- --cov -t node
  test-browser:
    needs: check
    runs-on: ubuntu-latest
    name: test ${{ matrix.project }} ${{ matrix.browser }} ${{ matrix.type }}
    strategy:
      matrix:
        project:
          - ipfs-repo
          - ipfs-repo-migrations
        browser:
          - chromium
          - firefox
        type:
          - browser
          - webworker
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      - run: npm run test -- --scope=${{ matrix.project }} -- -- -t ${{ matrix.type }} -- --browser ${{ matrix.browser }}
#   test-electron:
#     needs: check
#     runs-on: ubuntu-latest
#     name: test ${{ matrix.project }} ${{ matrix.type }}
#     strategy:
#       matrix:
#         project:
#           - ipfs-repo
#           - ipfs-repo-migrations
#         type:
#           - electron-main
#           - electron-renderer
#       fail-fast: true
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v1
#         with:
#           node-version: 16
#       - run: npm install
#       - uses: GabrielBB/xvfb-action@v1
#         with:
#           run: npm run test -- --scope=${{ matrix.project }} -- -- -t ${{ matrix.type }} --bail
