name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.npm
            ./node_modules
            ./packages/*/node_modules
            ./packages/*/dist
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - run: |
          npm install
          npm run build
          npx lerna link

  check:
    name: Check
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - uses: actions/cache@v2
      id: cache
      env:
        CACHE_NAME: cache-node-modules
      with:
        path: |
          ~/.npm
          ./node_modules
          ./packages/*/node_modules
          ./packages/*/dist
        key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        npm install
        npm run build
    - run: |
        npm run lint
        npm run dep-check -- -- -- -p
        npm run dep-check -- -- -- -- --unused

  test-node:
    needs: build
    runs-on: ${{ matrix.os }}
    name: Unit test ${{ matrix.project }} node ${{ matrix.node }} ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node: [16]
        project:
          - ipfs-repo
          - ipfs-repo-migrations
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: ${{ github.event.pull_request.commits }}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.npm
            ./node_modules
            ./packages/*/node_modules
            ./packages/*/dist
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npm run build
      - run: npm run test -- --since ${{ github.event.pull_request.base.sha }} --scope=${{ matrix.project }} -- -- --cov -t node

  test-browser:
    needs: build
    runs-on: ubuntu-latest
    name: Unit test ${{ matrix.project }} ${{ matrix.browser }} ${{ matrix.type }}
    strategy:
      matrix:
        project:
          - ipfs-repo
#          - ipfs-repo-migrations
        browser:
          - chromium
          - firefox
        type:
          - browser
          - webworker
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: ${{ github.event.pull_request.commits }}
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.npm
            ./node_modules
            ./packages/*/node_modules
            ./packages/*/dist
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npm run build
      - run: npm run test -- --since ${{ github.event.pull_request.base.sha }} --scope=${{ matrix.project }} -- -- -t ${{ matrix.type }} -- --browser ${{ matrix.browser }}

#   test-electron:
#     needs: build
#     runs-on: ubuntu-latest
#     name: test ${{ matrix.project }} ${{ matrix.type }}
#     strategy:
#       matrix:
#         project:
#           - ipfs-repo
#           - ipfs-repo-migrations
#         type:
#           - electron-main
#           - electron-renderer
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           fetch-depth: ${{ github.event.pull_request.commits }}
#       - uses: actions/setup-node@v1
#         with:
#           node-version: 16
#       - uses: actions/cache@v2
#         id: cache
#         env:
#           CACHE_NAME: cache-node-modules
#         with:
#           path: |
#             ~/.npm
#             ./node_modules
#             ./packages/*/node_modules
#             ./packages/*/dist
#           key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
#       - name: Install Dependencies
#         if: steps.cache.outputs.cache-hit != 'true'
#         run: |
#           npm install
#           npm run build
#       - run: npm install
#       - run: npm run build
#       - uses: GabrielBB/xvfb-action@v1
#         with:
#           run: npm run test -- --since ${{ github.event.pull_request.base.sha }} --scope=${{ matrix.project }} -- -- -t ${{ matrix.type }} --bail
